reference: PATH/TO/YOUR/hg19.fasta

multi_cores: 4

general_settings:
 min_amp: 2
 min_frac: 1
 fuzziness: 0
 min_read_pos: 2
 min_read_pos_fraction: 10
 mq: 17
 bq: 17
 nr_amplicon: 2

germline_settings:
 min_depth_normal: 100

somatic_settings:
 min_depth_normal: 100
 min_depth_tumor: 100
